"""Add missing aircraft columns

Revision ID: 6d52d803eeb7
Revises: 396797cd1ca1
Create Date: 2025-04-11 20:37:51.382845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d52d803eeb7'
down_revision = '396797cd1ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('make', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('engine_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('num_engines', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ifr_equipped', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gps', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('autopilot', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hobbs_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tach_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_maintenance', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=100), nullable=True))
        batch_op.alter_column('make_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.alter_column('make_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('image_filename')
        batch_op.drop_column('last_maintenance')
        batch_op.drop_column('tach_time')
        batch_op.drop_column('hobbs_time')
        batch_op.drop_column('autopilot')
        batch_op.drop_column('gps')
        batch_op.drop_column('ifr_equipped')
        batch_op.drop_column('num_engines')
        batch_op.drop_column('engine_type')
        batch_op.drop_column('category')
        batch_op.drop_column('description')
        batch_op.drop_column('model')
        batch_op.drop_column('make')

    # ### end Alembic commands ###
