"""Initial migration

Revision ID: 76850f1dece2
Revises: 
Create Date: 2025-03-30 11:43:50.306951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76850f1dece2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
